return {
	require("plugins.ui"),
	require("plugins.lsp"),
	require("plugins.cmp"),
	require("plugins.treesitter"),
	require("plugins.telescope"),
	require("plugins.git"),
	require("plugins.formatter"),
	require("plugins.linting"),
	require("plugins.debug"),
	require("plugins.explorer"),
	require("plugins.whichkey"),
	require("plugins.comment"),
	require("plugins.editor"),
	require("plugins.webdev"),
	require("plugins.mason-tools"),
}
